-- lua/core/init.lua

-- Load all plugin files
require("core.plugin.kanagawa")
require("core.plugin.fugitive")
require("core.plugin.harpoon")
require("core.plugin.lsp-zero")
require("core.plugin.mason")
require("core.plugin.telescope")
require("core.plugin.treesitter")
require("core.plugin.undotree")
require("core.plugin.project")
require("core.plugin.nvim-tree")
require("core.plugin.multicursors")
require("core.plugin.black")
require("core.plugin.prettier")
require("core.plugin.autoclose")
require("core.plugin.workspaces")
require("core.plugin.cmp")
require("core.plugin.snippets")
require("core.plugin.luasnip")
require("core.plugin.oil")
require("core.plugin.toggleterm")
require("core.plugin.nvim-window")
require("core.plugin.glow")
-- require("core.plugin.auto-header")
-- require("core.plugin.rmarkdown")
require("core.plugin.markdown")
require("core.plugin.live-server")
-- require("core.plugin.copilot")
-- require("lua.core.plugin.nvim-java")
-- require("core.plugin.supermaven")



